{{- if .Values.bookings.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: bookings
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: bookings
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.bookings.appPort }}
{{- end }}