{{- if .Values.customers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - name: customers
        image: {{ .Values.customers.image.repo }}:{{ .Values.customers.image.tag }} # Replace with your Docker image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.customers.appPort }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.customers.appPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.customers.appPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
{{- end }}