{{- if .Values.customers.enabled }}
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: customers
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.kong.name }}
      namespace: {{ .Values.kong.namespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.customers.http.route }}
      backendRefs:
        - name: customers
          port: 80
{{- end }}